[template]
keys = [
  "services"
]

owner = "haproxy"
mode = "0644"
src = "certs.tmpl"
dest = "/tmp/certs.pem"

reload_cmd = "cert_splitter.sh && haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)"
